name: CI

on:
  push:
    branches-ignore:
      - main
jobs:
  ci:
    name: continuous integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      #      - name: linting
      #        uses: golangci/golangci-lint-action@v3
      #        with:
      #          version: v1.46.2
      - name: unit testing
        run: |
          make unit_testing
