name: Publish package

on:
  push:
    tags:
      - 'v*'

jobs:
  releases-matrix:
    name: Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
        exclude: # We don't want arm binaries for windows
          - goarch: arm64
            goos: windows
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: release
        uses: wangyoucao577/go-release-action@v1.24
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "ptf"
